# Generated by Django 4.2.7 on 2023-11-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='atividades',
            new_name='atividade',
        ),
    ]
